language: c
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "DHT sensor library"
script:
  - arduino --verify --board esp8266:esp8266:huzzah $PWD/cloud_data_logger/cloud_data_logger.ino
  - arduino --verify --board esp8266:esp8266:huzzah $PWD/dht_test/dht_test.ino
notifications:
  email:
    on_success: change
    on_failure: change